name = "cloud-nav"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "jiugenav"
database_id = "ba95fd9d-5306-4cee-b3c0-b141ca87a776"
migrations_dir = "drizzle"

[ai]
binding = "AI"